### ISSUE TITLE
[iPhone12] Screen Size Error

### ISSUE THREAD

**Issue by UnityKR** [googlevr/cardboard#144]
iPhone12 Pro Max
iPhone12

iOS 14.1
Cardboard XR SDK 130
Unity 2019.4.5f1

VR Rendering Scale Problem.
How to fix it.

iPhone12 pro max

![iPhone12 pro max Screen](https://user-images.githubusercontent.com/46150621/96988974-06334880-1560-11eb-9012-544b965b0766.PNG)

iPhone12

![iPhone12 Screen](https://user-images.githubusercontent.com/46150621/96980966-78089380-155a-11eb-990e-95f017b24c26.PNG)

**Comment by jballoffet** [comment]
Thanks for reporting this issue. A fix for this has just been submitted and it will be included in the next release. In case you cannot wait until v1.4.0 is out, you can apply the required changes by yourself. In order to do so, you just need to add the correct DPIs for 2020 iPhone models in this [file](https://github.com/googlevr/cardboard/blob/master/sdk/screen_params/ios/screen_params.mm), by applying the following patch:
```bash
diff --git a/sdk/screen_params/ios/screen_params.mm b/sdk/screen_params/ios/screen_params.mm
index 69ce5b9..90c1c12 100644
--- a/sdk/screen_params/ios/screen_params.mm
+++ b/sdk/screen_params/ios/screen_params.mm
@@ -47,6 +47,10 @@ NSString *const kGIPDeviceGenerationiPhone11 = @"iPhone 11";
 NSString *const kGIPDeviceGenerationiPhone11Pro = @"iPhone 11 Pro";
 NSString *const kGIPDeviceGenerationiPhone11ProMax = @"iPhone 11 Pro Max";
 NSString *const kGIPDeviceGenerationiPhoneSimulator = @"iPhone Simulator";
+NSString *const kGIPDeviceGenerationiPhone12Mini = @"iPhone 12 Mini";
+NSString *const kGIPDeviceGenerationiPhone12 = @"iPhone 12";
+NSString *const kGIPDeviceGenerationiPhone12Pro = @"iPhone 12 Pro";
+NSString *const kGIPDeviceGenerationiPhone12ProMax = @"iPhone 12 Pro Max";
 
 // DPI for iPhone (default) and iPhone+: http://dpi.lv/
 static CGFloat const kDefaultDpi = 326.0f;
@@ -54,6 +58,8 @@ static CGFloat const kIPhonePlusDpi = 401.0f;
 static CGFloat const kIPhoneOledDpi = 458.0f;
 static CGFloat const kIPhoneXrDpi = 324.0f;
 static CGFloat const kIPhoneXsMaxDpi = 456.0f;
+static CGFloat const kIPhone12MiniDpi = 476.0f;
+static CGFloat const kIPhone12Dpi = 460.0f;
 
 CGFloat getDpi() {
   // Gets model name.
@@ -103,6 +109,10 @@ CGFloat getDpi() {
     @"iPhone12,1" : kGIPDeviceGenerationiPhone11,
     @"iPhone12,3" : kGIPDeviceGenerationiPhone11Pro,
     @"iPhone12,5" : kGIPDeviceGenerationiPhone11ProMax,
+    @"iPhone13,1" : kGIPDeviceGenerationiPhone12Mini,
+    @"iPhone13,2" : kGIPDeviceGenerationiPhone12,
+    @"iPhone13,3" : kGIPDeviceGenerationiPhone12Pro,
+    @"iPhone13,4" : kGIPDeviceGenerationiPhone12ProMax,
   };
   NSString *model = models[modelName];
   if (!model) {
@@ -135,6 +145,10 @@ CGFloat getDpi() {
     kGIPDeviceGenerationiPhone11 : @(kDefaultDpi),
     kGIPDeviceGenerationiPhone11Pro : @(kIPhoneOledDpi),
     kGIPDeviceGenerationiPhone11ProMax : @(kIPhoneOledDpi),
+    kGIPDeviceGenerationiPhone12Mini : @(kIPhone12MiniDpi),
+    kGIPDeviceGenerationiPhone12 : @(kIPhone12Dpi),
+    kGIPDeviceGenerationiPhone12Pro : @(kIPhone12Dpi),
+    kGIPDeviceGenerationiPhone12ProMax : @(kIPhoneOledDpi),
   };
 
   NSNumber *dpi = dpis[model];
@@ -154,3 +168,4 @@ void getScreenSizeInMeters(int width_pixels, int height_pixels, float* out_width
 
 }  // namespace screen_params
 }  // namespace cardboard
+
```

**Comment by Excubitor** [comment]
What do you have to do if you are using the unity package?

**Comment by chaosemer** [comment]
This was fixed in v1.4.0.

**Comment by AndrewSpalato-FGMNT** [comment]
@Excubitor @jballoffet Do you know where to find the file "screen_params.m"m or "screen_params.h" in Xcode?
I am using the Cardboard XR plugin for Unity.

**Comment by AndrewSpalato-FGMNT** [comment]
@chaosemer I tried v1.4.0 still getting this issue on iPhone 12

**Comment by BRM15538** [comment]
Hello everyone! sorry for the ignorance about my question, but, how can i update from version 1.23 to the version 1.4? every time when i click on update button doesn't happen nothing
blessings for all!
<img width="853" alt="image" src="https://github.com/googlevr/cardboard/assets/110194107/037c6d42-bdbb-4a6b-8fd4-6b771dccc3d2">
