### ISSUE TITLE
Additional "depth only" HUD camera flickers on iOS with Metal

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/cardboard#286]
Edit 1: Added iOS and iPhone versions.
Edit 2: Added build method.
Edit 3: Added 1.7.0

We are using a two-camera setup for displaying HUD. Our 2nd HUD camera is a "depth only" camera (see screenshot). We were using OpenGL on iOS without a problem, but due to random crashes, while switching between VR and non-VR modes, we need to migrate from OpenGL to Metal on iOS. However, the content of our HUD camera flickers continuously (see video and repro project attached).

Currently, we are stuck between a randomly crashing app during VR mode switches (deprecated OpenGL), and an unusable app with flickering HUD (Metal). This is a live app on the stores, so I appreciate any workaround or quick fix until the issue is addressed in a future SDK update.

- Unity 2019.4.28f1 and 2020.3.14f1
- Cardboard 1.6.0 and 1.7.0
- Built using Unity cloud builder.

- Works fine on Android.
- Works fine with OpenGL on iOS.

Reproduced with (All iOS 14.6):
- iPhone9,4
- iPhone13,3
- iPad7,5

REPRO PROJECT:
[FlickerTest.zip](https://github.com/googlevr/cardboard/files/6873135/FlickerTest.zip)

VIDEO:
https://user-images.githubusercontent.com/19275187/126882399-044f10c4-80ad-43c4-b7ca-3460d802bf24.mp4

SCREENSHOT:
![image](https://user-images.githubusercontent.com/19275187/126882393-6ac2846f-9f27-41b6-91a9-0d802330d02c.png)

SETUP:
![image](https://user-images.githubusercontent.com/19275187/126882324-b68dc00b-2119-4a0a-82ad-e3536c503db5.png)

**Comment by guneyozsan** [comment]
The issue persists in cardboard 1.7.0 tested with Unity 2020.3.14f1.

**Comment by guneyozsan** [comment]
@jballoffet I noticed the label update as a bug, thanks! Any chance this goes into the next release? Or, any expected timeline?

Asking because our app is live on stores and this blocks us from migrating to Metal. Currently, we are stuck with a randomly crashing OpenGL app when exiting VR mode (also crashes %99 of the VR mode switches on iPhone 12).

Or, are there any workarounds suggested meanwhile?

**Comment by julien-tamade** [comment]
Yeah I'm getting flicker not using any additional depth only camera. Just a single camera. Using metal with 2019.4.30f1 and cardboard v1.8

**Comment by guneyozsan** [comment]
@julien-tamade Considering your video, are you using a skybox? The resulting effect is the same as the camera-on-camera setup.

**Comment by julien-tamade** [comment]
@guneyozsan I am using a skybox

**Comment by julien-tamade** [comment]
@jballoffet is there any intention to look into this issue? Worried my app will be killed any second because GLE2 is deprecated and who knows when it will stop working in some iOS update.

**Comment by guneyozsan** [comment]
Unity says 2019.4 will be obsolete in spring 2022. Any plans fixing this issue until that?

From https://unity3d.com/unity/qa/lts-releases
_Unity 2019.4 is now the legacy LTS; it will be updated monthly until it reaches the end of its support cycle in spring 2022._

**Comment by jballoffet** [comment]
Sorry for the long delay here. Thanks @guneyozsan for the repro project, I confirm that I’m able to reproduce the issue on an iPhone SE. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by guneyozsan** [comment]
@jballoffet Thank you! It is relieving to hear this.

**Comment by julien-tamade** [comment]
Hi @jballoffet Was wondering if you had and update or idea of timeline for this bug? Thank You!

**Comment by julien-tamade** [comment]
Hey @guneyozsan, I'm curious if you have found any workarounds for this issue? Thanks!

**Comment by guneyozsan** [comment]
@julien-tamade our workaround is using Unity 2019.4 LTS and OpenGL for iOS.

(However, with OpenGL on iOS app was crashing when switching from VR to 2D mode. We had to delay for a couple of frames the `Instantiate()` functions called when the 2D scene was loaded after VR mode.)

**Comment by julien-tamade** [comment]
@guneyozsan, thanks for the response.

We're still using 2019.4 LTS and openGL as well but are desperately trying to switch to metal cus there's so many crashes occurring at startup. Luckily we rarely have crashes at runtime, but there's tons of initializing crashes that are users are dealing with. And since upgrading to cardboard 1.9 to get support for iPhone 13, our app doesn't work at all on iPhone 6s anymore lol

For switching between 2D and VR we have two separate cameras for that which may have gotten around the issue you were describing. 

@jballoffet any idea on when we can expect this issue to be fixed?

**Comment by guneyozsan** [comment]
We stopped at `v1.4.1`. Not trying the new versions until the resolution, any issue causes too much dev time lost.

We also have crashes right on launch but not that frequent. However, this is only for our devices. Crash frequency pretty randomly differs per iPhone model, probably due to unsupported driver.

**Comment by julien-tamade** [comment]
Not sure if @jballoffet is still active on this, but was wondering if anybody else has an update on this issue? @xinyunh0929 @chaosemer

**Comment by jballoffet** [comment]
@julien-tamade, unfortunately, we haven't been able to prioritize this issue yet. At the moment, we are focusing on getting Vulkan support out. I'll update this ticket once we have some news about it. Thanks!

**Comment by andrewio** [comment]
Hi, I can confirm that this issue (flickering of game objects & UI) exists for Unity 2020 & Unity 2021. 

I use the 2nd camera (Depth Only) to implement Mixed Reality feature in my [Unity Asset](https://makaka.org/o/mr-camera). 

So my asset was tested & works perfectly in next Environment: 
- 2019.4.17 
- Google Cardboard XR Plugin for Unity 1.4.1.

The asset is not updated for about a year and my new clients continue to use it without issues, so I can guess that the asset works in the latest versions of Unity 2019.4.x & Google Cardboard XR Plugin.

This bug makes it impossible to use the asset with Unity 2020 & Unity 2021. Please fix this issue.

**Comment by guneyozsan** [comment]
@andrewio It works with Unity 2019.4.x because it uses OpenGL. The issue is specific to Metal and it is the only option for Unity 2020 and later as OpenGL on iOS is deprecated.

**Comment by jballoffet** [comment]
A fix (workaround for https://fogbugz.unity3d.com/default.asp?1427493_c43j6si13dh08epg) for this issue has been submitted and it will be included in the next release of Cardboard. Thanks for reaching out!

**Comment by julien-tamade** [comment]
@jballoffet amazing! very excited for this. Will this require just an update to the Cardboard sdk or will we need to update unity version?

**Comment by jballoffet** [comment]
The workaround will require an update on the Cardboard XR Plugin version. So far, the fix has been tested using the repro project and Unity 2020.3.32f1. HTH

**Comment by GabrielR** [comment]
@jballoffet is there a publicly available branch with this fix so we can try it out?  I have a hard client deadline that's blocked by this issue.  Would be happy to help as a beta tester

**Comment by GabrielR** [comment]
@jballoffet   That's great!   Thank you so much for that patch.  I didn't expect it at all. Thank you for going the extra distance to help us out.

**Comment by xinyunh0929** [comment]
This was fixed in v1.16.0.

**Comment by julien-tamade** [comment]
@xinyunh0929  @jballoffet 
I'm still facing this issue on one of my scenes. I have about 20 scenes and haven't tested them all but I've encountered this issue so far. This was tested on an iPhone SE 2nd Gen running iOS 15.5 and Unity 2019.4.40f1 with Cardboard sdk 1.16.0. 

The flicker isn't consistent. sometimes it's really bad and sometimes it's only a couple of flickers. It usually goes away at some point but i've seen it come back as well. I find if you restart the app a few times you're likely to see the flickering at some point.

Here's a link to the video and sample project:
[https://drive.google.com/drive/folders/1Sy0dGtSXUdmcdE_Fb6VUo5PF3HXSZxYs?usp=sharing](https://drive.google.com/drive/folders/1Sy0dGtSXUdmcdE_Fb6VUo5PF3HXSZxYs?usp=sharing)
