### ISSUE TITLE
Bitcode bundle Error

### ISSUE THREAD

**Issue by Archi97** [googlevr/cardboard#355]
### SPECIFIC ISSUE ENCOUNTERED
I have updated the Plugin to the latest one. I also have Latest firebase Crashlytics(8.10.1) which is automatically uploading debug symbols to make crashes more readable. After that i can build and test the application but i can't archive it to distribute.

### EXPECTED BEHAVIOR
It should archive without any problems.

### VERSIONS USED
Cardboard SDK/Cardboard XR Plugin 1.15.0
Unity 2020.3.15f2

### SCREENSHOTS
![image](https://user-images.githubusercontent.com/36793459/169971650-030f6217-b5b8-44c5-a35e-cb3eedb70598.png)

**Comment by GabrielR** [comment]
If you built your own graphics library, then you probably have the same issue I had.   To make this work you'd need to create a Fat Library where you make multiple builds for different targets and then merge them together. 

However, I recently learned Bitcode for iOs builds is being depreciated and will be removed from XCode 14.  The app store will take a build without Bitcode, the problem is Unity is forcing a Bitcode build.  You need to remove that setting from the Unity build.  

Make an Editor script (in an /editor/ folder in Unity) from the code below. The next time you build in Unity it will create a build with 'Enable Bitcode = off'.   If you're using a Workspace file, set Enable Bitcode to false in the target Build Settings. 

```
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;


// This editor post process removes all the bitcode enabled settings from the iOs build.  
// Unity apparently has a requirement burried deep that uses bitcode

public class DisablingBitcodeiOS
{
    [PostProcessBuild(1000)]
    public static void PostProcessBuildAttribute(BuildTarget target, string pathToBuildProject)
    {
        if (target == BuildTarget.iOS)
        {
            string projectPath = PBXProject.GetPBXProjectPath(pathToBuildProject);

            PBXProject pbxProject = new PBXProject();
            pbxProject.ReadFromFile(projectPath);
#if UNITY_2019_3_OR_NEWER
            var targetGuid = pbxProject.GetUnityMainTargetGuid();
#else
                var targetName = PBXProject.GetUnityTargetName();
                var targetGuid = pbxProject.TargetGuidByName(targetName);
#endif
            pbxProject.SetBuildProperty(targetGuid, "ENABLE_BITCODE", "NO");
            pbxProject.WriteToFile(projectPath);

            var projectInString = File.ReadAllText(projectPath);

            projectInString = projectInString.Replace("ENABLE_BITCODE = YES;",
                $"ENABLE_BITCODE = NO;");
            File.WriteAllText(projectPath, projectInString);
        }
    }
}
```

I found this code on a Unity forum. I no longer have the link.

**Comment by jballoffet** [comment]
A fix for this issue has been submitted and it will be included in v1.18.0. Thanks for reaching out!

**Comment by xinyunh0929** [comment]
This was fixed in v1.18.0.

**Comment by dletozeun** [comment]
Hi,

@jballoffet @xinyunh0929 the problem persists in v1.18.1 at least in the released unity integration here: https://github.com/googlevr/cardboard-xr-plugin/tree/v1.18.1.

I have rebuilt the static library following these instructions: https://developers.google.com/cardboard/develop/ios/quickstart#download_and_build_the_demo_app

I had to enable bitcode in `sdk` and `Pods` projects and you'll see the generated `GfxPluginCardboard.a` static library is slightly bigger than the one released. Is there a mistake?

I have patched the `GfxPluginCardboard.a` library on my side and I can now build with bitcode my Unity project.
