### ISSUE TITLE
Address config/build warnings for Cardboard SDK with NDK v27.X

### ISSUE THREAD

**Issue by tellypresence** [googlevr/cardboard#476]
When building Cardboard SDK with Android Studio Koala Feature Drop Patch 1 and NDK v27.X (supported since Cardboard v1.26.0) several warnings are reported.  It would be good to address the root causes in an effort to make the build warning-free.

### `SDK XML version 4 was encountered` warning
```
> Task :sdk:sdk:configureCMakeDebug[arm64-v8a]
[CXX5304] This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. 
This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
```

### Missing `project()` command in `CMakeLists.txt`:
```
C/C++: CMake Warning (dev) in CMakeLists.txt:
C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
C/C++:   contain a literal, direct call to the project() command.  Add a line of
C/C++:   code such as
C/C++:     project(ProjectName)
C/C++:   near the top of the file, but after cmake_minimum_required().
C/C++:   CMake is pretending there is a "project(Project)" command on the first
C/C++:   line.
C/C++: This warning is for project developers.  Use -Wno-dev to suppress it.
```

### Missing field initializer warnings in 3 source files:
```
<...>/cardboard/sdk/rendering/android/vulkan_distortion_renderer.cc
<...>/cardboard/sdk/unity/xr_unity_plugin/vulkan/vulkan_renderer.cc
<...>/cardboard/sdk/unity/xr_unity_plugin/vulkan/vulkan_widgets_renderer.cc
```
e.g.
```
C/C++: <...>/cardboard/sdk/rendering/android/vulkan_distortion_renderer.cc:190:49: warning: 
    missing field 'pNext' initializer [-Wmissing-field-initializers]
C/C++: 15 warnings generated.

Also in vulkan_renderer.cc
C/C++: <...>/cardboard/sdk/unity/xr_unity_plugin/vulkan/vulkan_renderer.cc:308:5: warning: 
    missing field 'flags' initializer [-Wmissing-field-initializers]
C/C++: 10 warnings generated.

C/C++: <...>/cardboard/sdk/unity/xr_unity_plugin/vulkan/vulkan_widgets_renderer.cc:134:74: warning: 
    missing field 'pNext' initializer [-Wmissing-field-initializers]
C/C++: 14 warnings generated.
```

### `invalid ABI 'riscv64'` configuration warning
There's also this warning; not sure if it's Cardboard-specific or due to NDK v27.X
```
WARNING: C/C++: Ignoring invalid ABI 'riscv64' found in ABI metadata file 
    '<...>/Android/Sdk/ndk/27.1.12297006/meta/abis.json'.
C/C++: Ignoring invalid ABI 'riscv64' found in ABI metadata file '<...>/Android/Sdk/ndk/27.1.12297006/meta/abis.json'.
```

**Comment by arilow** [comment]
Thank you for reporting this issue. I confirm I’m able to repro de issue locally. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.

**Comment by Voldivh** [comment]
Hi @tellypresence this issue have been fixed internally and should be rolled out during the next release on version 1.30. Once again, thanks a lot for raising this issue and helping us improve!

**Comment by xinyunh0929** [comment]
This was fixed in v1.30.0.

**Comment by tellypresence** [comment]
In v1.31.0 two of the warnings no longer appear, but still getting the `missing field 'flags' initializer` warnings
```
C/C++: <cardboard path>/sdk/unity/xr_unity_plugin/vulkan/vulkan_renderer.cc:312:5: warning: 
    missing field 'flags' initializer [-Wmissing-designated-field-initializers]
C/C++:   312 |     };
```

Also, it seems that the NDK was downgraded from v27 to `26.1.10909125` in a recent release, is that correct?
