### ISSUE TITLE
Turning off VR

### ISSUE THREAD

**Issue by NicolasBegin** [googlevr/cardboard#59]
I saw this (closed) issue and tried it cause it's what I need : https://github.com/googlevr/cardboard/issues/45

But when I use **_XRGeneralSettings.Instance.Manager.StopSubsystems()_** the camera freeze, or stop rendering, and the last cardboard frame stay displayed until I use **_XRGeneralSettings.Instance.Manager.StartSubsystems()_** again to reactivate VR.

I did it on a blank project with only the Google Cardboard sample.

Is there something more to do to disable VR ?

Unity 2019.3.15f1
XR Plugin Management 3.2.10
Cardboard XR Plugin for unity 1.1.0

**Comment by friggasaint** [comment]
As far as I see it in this case the camera doesn't stop rendering.
It is just, that you don't have any means of interaction in that scene if you turn VR off.
You would need to implement e.g. camera movement if you turn off VR.

As I stated  in the other post we use 
`XRGeneralSettings.Instance.Manager.StopSubsystems()`
`cam.ResetAspect();`
which almost gives the same effect as VR being turned off with the ability to turn VR on again

Problem which still stands:
I believe to work as intended one would use
`XRGeneralSettings.Instance.Manager.StopSubsystems();
XRGeneralSettings.Instance.Manager.DeinitializeLoader();`
But this doens't give a good result on our side.
VR Switch on
![Screenshot_20200526-005918](https://user-images.githubusercontent.com/1319045/84174527-01716a80-aa7f-11ea-89e9-05b8f4e164ce.png)
VR Switch off
![Screenshot_20200526-005930](https://user-images.githubusercontent.com/1319045/84174536-033b2e00-aa7f-11ea-9822-b548516cb437.png)
Also also turning on VR again with
`XRGeneralSettings.Instance.Manager.InitializeLoader()`  _async_
`XRGeneralSettings.Instance.Manager.StartSubsystems() `
crashes our application.

**Comment by NicolasBegin** [comment]
When I switch off VR I don't have the second image, I stay on the first until I switch it on again...
The close cross and screen-click stay active, I can quit the app or interact with object while VR is disabled. Screen click is blind click cause nothing move, but that works.

I checked the guidestart multiple times and remade a blank project but it doesn't changed anything :(

I looked at the logs and it says : 
`[XR] [CardboardXrInputProvider]: Lifecycle stopped`
Do you have any idea ?

I have a Xperia XZ with Android  8.0, maybe I should try an other phone...

**Comment by ZioCain** [comment]
I'm having the same problem as you, but I know that the check under XR Plugin Manager "Initialize at startup" must be unchecked

**Comment by NicolasBegin** [comment]
I tried to uncheck it and Init VR by code.
Init and start worked but nothing changed on stop

**Comment by nukadelic** [comment]
Any updates on this ?

**Comment by RajatPatel5** [comment]
When using the plugin I can successfully start the VR and also turn on and off VR. I am manually initializing VR with `UnityEngine.XR.Management.XRGeneralSettings.Instance.Manager.InitializeLoaderSync();` but the issue is once the left the VR scene and come back and when initialize is called again the app crashes. 
Does anyone have the same kind of issue and anyone got any temporary fix for it?

**Comment by D3m0n92** [comment]
Same problem... any solution?

**Comment by D3m0n92** [comment]
Solution: https://assetstore.unity.com/packages/tools/camera/cardboard-net-168945

Buy this package (the cost is very sustainable) and you will solve all the problems of this officially shameful SDK. I solved it this way.

**Comment by SamTrudgianMelody** [comment]
I am not able to see the cardboard UI once cardboard has been initialized with UnityEngine.XR.Management.XRGeneralSettings.Instance.Manager.InitializeLoaderSync(); but the FOV get's changed. Might anyone know why the left and right eye rendering is not being setup properly on the main camera? Thx

**Comment by julien-tamade** [comment]
Any update on this?

**Comment by JoaoBorks** [comment]
Guys, I have a solution for this. I was experiencing the same visual artifact, and it can be solved easily by calling [`camera.ResetAspect()`](https://docs.unity3d.com/ScriptReference/Camera.ResetAspect.html) after `DeInitialize` as @friggasaint pointed out. To avoid crashes, I suggest you implement the changes from this PR #124 ([download here](https://github.com/googlevr/cardboard/files/5313673/GoogleCardboardXR.zip)). Also, bump the PR so it gets merged!

**Comment by chaosemer** [comment]
The core issue of rendering not working after toggling VR on and off is fixed in the upcoming release.

After this fix lands, you will still need to call `camera.ResetAspect()` as @JoaoBorks suggests. This is required by Unity and outside of the control of the Cardboard XR plugin.

**Comment by chaosemer** [comment]
This was fixed in v1.3.0.

**Comment by honkeat** [comment]
This is not fixed. The single view camera still doesn't move after toggled from VR view.
